### ISSUE TITLE
The meaning of '-sampling_intvl' in hotspot.config

### ISSUE THREAD

**Issue by AaAaYou** [uvahotspot/HotSpot#1]
### Problem statement
I can't understand the parameter "**-sampling_intvl**" in _hotspot.config_ , could i regard -**_sampling_intvl_** as power trace transient step?

I referred to the source code and other useful documents, and pose below :

1. _average power is simply (#events*Eevent)/timestep_ from **FAQ**
2. _'power' array is an aggregate of per cycle numbers over the sampling_intvl. so, compute the average power_  from **sim-template.c**
3. _sampling rate of 100-300 KHz (i.e., a period of 3.3 - 10 microsec.) gives excellent precision with negligible slowdown_ from **FAQ**
4. _assume instantaneous leakage update with increased temperature in each transient step 
('sampling interval') in HotSpot._ from **HOW-TO**

**Comment by westre3** [comment]
Yes, your intuition is correct. The "**-sampling_intvl**" parameter is the amount of time between each power trace specified in the power trace file. The first power trace specifies the power dissipation at time **t=0**, the second power trace specifies the power dissipation at **t=sampling_intvl**, the third power trace specifies the power dissipation at time **t=2*sampling_intvl**, etc.

For faster answers to any future questions, please email hotspot@virginia.edu.

**Comment by AaAaYou** [comment]
Extremely grateful!
