### ISSUE TITLE
Hotspot shows me Unknown options massage

### ISSUE THREAD

**Issue by explorer1022** [uvahotspot/HotSpot#2]
Hello
when I run this command hotspot -c hotspot.config -f ev6.flp -p gcc.ptrace on the hotspot it shows an error message, I installed it on the ubuntu 20.

ahmad@ahmad-VirtualBox:~/HotSpot$ hotspot -c hotspot.config -f ev6.flp -p gcc.ptrace

Unknown options: c, f, p

**Comment by westre3** [comment]
Could you provide a screenshot of the contents of your `~/HotSpot/` directory, along with a screenshot of you running that command and the error message you're receiving?

**Comment by explorer1022** [comment]
![HotSpot1](https://user-images.githubusercontent.com/67677402/88417883-a4393a80-cdda-11ea-86fe-835f95442827.PNG)
![HotSpot_2](https://user-images.githubusercontent.com/67677402/88417943-b9ae6480-cdda-11ea-9cd9-38d041b1cc3c.PNG)

**Comment by westre3** [comment]
Have you tried executing "./hotspot" instead of just "hotspot" to make sure that you're using the executable in that directory? I don't believe that HotSpot ever uses the error string "Unknown options", which makes me believe that may be an error message that your system is generating and not that HotSpot is generating.

**Comment by explorer1022** [comment]
many thank for your reply on my message.
it works with me now.
Kind regards
Farhan

**Comment by explorer1022** [comment]
Hello
Is there any way to converting mcpat log into ptrace (hotspot format)?
Kind regards
Farhan

**Comment by westre3** [comment]
I suspect you could write a script to take care of the conversion, but we don't currently have a canonical way of converting between those formats.
